version: "3.8"

services:
  postgres:
    image: "postgres:alpine"
    container_name: cockroachdb
    environment:
      POSTGRES_DB: cockroach
      POSTGRES_PASSWORD: 123456
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
